language: node_js
node_js:
- '6.9'
sudo: true
env:
  global:
  - CF_APP=smarthome-svc
  - CF_API=https://api.eu-gb.bluemix.net
  - CF_USERNAME=pbochynski@gmail.com
  - CF_ORGANIZATION=iothome
  - CF_SPACE=dev
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: develop
services:
  - mongodb